### ISSUE TITLE
[Bug]: AmpliCLI won't recognize events

### ISSUE THREAD

**Issue by igor9silva** [amplitude/amplitude-dev-center#27]
### What happened?

We're using the AmpliCLI to have typed event calls on a Vue 3 project. However, there AmpliCLI isn't event to properly identify event calls implementations (through `ampli status`). It reports as if none were implemented.

We have a custom hook to expose the Ampli Wrapper to the app, this may be leading the CLI to misbehave.

We use it like that:
```javascript
import { useAnalytics } from '@/utils/useAnalytics';
const analytics = useAnalytics();
analytics?.sampleEvent({
  name: props?.name,
});
```

The hook:
```javascript
import { Environment, Ampli, ampli } from './ampli';
import { useRuntimeConfig } from '#imports';
import { User } from '@/types/User';

const _client = ampli as Ampli & {
	identifyUser: (user: User) => void;
	resetUser: () => void;
};

const identifyUser = (user: User) => {
	// Prepend user ID with 0's to make it have *at least* 5 digits.
	// 	104 -> 00104
	// 	104017 -> 104107
	// Logic was replicated from `portal-web`, but with a different implementation:
	// 	https://github.com/onovomercado/portal-web/blob/d9987a6aff4a0fad3f5a69c84c11665612a6423d/src/app/auth/Login.vue#L192
	_client.identify(user.id.toString().padStart(5, '0'));
};

const resetUser = () => _client.client?.reset();

const initialize = () => {
	const config = useRuntimeConfig();
	const environment = config.public.AMPLITUDE_ENVIRONMENT as Environment;

	_client.identifyUser = identifyUser;
	_client.resetUser = resetUser;
	_client.load({ environment });
};

export const useAnalytics = () => {
	if (!_client.isLoaded) initialize();
	return _client;
};

```

**Comment by markzegarelli** [comment]
Hi @igor9silva, issues in this repository are meant specifically for documentation issues. For support with your issue, I recommend the [Amplitude Community](https://community.amplitude.com/?utm_source=devdocs&utm_medium=helpcontent&utm_campaign=devdocswebsite) or submitting a ticket [here](https://help.amplitude.com/hc/en-us/requests/new).

Any documentation issues raised from this will come back to us to update.

**Comment by igor9silva** [comment]
Thanks for the reference @markzegarelli
